### ISSUE TITLE
Add typing information to private chats.

### ISSUE THREAD

**Issue by AndFChat** [AndFChat/AndFChat#38]

**Comment by AndFChat-Pandora** [comment]
Not sure how to help fix this problem, as I don't understand what this means.

**Comment by AndFChat** [comment]
In the web chat there is a text on the bottom "XYZ is typing" "XYZ stopped typing". Those are some token that can be send/received by client but still not evaluated.

**Comment by AndFChat-Pandora** [comment]
This will be included in the upcoming update.
