### ISSUE TITLE
Bookmarkable Channels instead of opening only one all the time.

### ISSUE THREAD

**Issue by AndFChat** [AndFChat/AndFChat#45]

**Comment by AndFChat-Pandora** [comment]
You will be able to open multiple channels on login with the next update

Motion to close.

**Comment by AndFChat** [comment]
does this work for non-official channels too? :)

**Comment by AndFChat-Pandora** [comment]
Not yet. I'll look into that, though.

**Comment by AndFChat-Pandora** [comment]
Auto-join for private rooms will be available in the next version.
